name: deploy

on:
  push:
    branches:
      - master
      - deploy-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"

      - run: mvn package

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.LAMBDA_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy lambda
        run: >
          aws lambda update-function-code 
          --function-name ${{ secrets.LAMBDA_POST_ARN }} 
          --zip-file  fileb://target/NovelLambdaPost.jar 
          --publish
